import { Link } from 'react-router';
import { Button } from '../components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../components/ui/card';
import {
  Target,
  Brain,
  TrendingUp,
  GraduationCap,
  Sparkles,
  Route,
  BarChart3,
  Building2,
  MessageCircle,
  CheckCircle2,
  ArrowRight,
  Zap,
  Users,
  Globe2,
  BookOpen,
  Award,
  Rocket,
  Star,
  ChevronRight,
  Briefcase
} from 'lucide-react';
import { Navbar } from '../components/Navbar';

export function HomePage() {

  const features = [
    {
      icon: Target,
      title: 'Smart Course Recommendations',
      description: 'AI-powered course suggestions perfectly matched to your career goals and current skills.',
      color: 'from-violet-500 to-purple-600'
    },
    {
      icon: TrendingUp,
      title: 'Skill Gap Analysis',
      description: 'Identify missing skills for your dream job and find courses to close those gaps.',
      color: 'from-cyan-500 to-blue-600'
    },
    {
      icon: Route,
      title: 'AI Career Roadmap',
      description: 'Get a personalized week-by-week learning roadmap generated by Gemini AI.',
      color: 'from-emerald-500 to-green-600'
    },
    {
      icon: BarChart3,
      title: 'Career Overview Dashboard',
      description: 'Track your skills mastered, progress, and job readiness score in real-time.',
      color: 'from-amber-500 to-orange-600'
    },
    {
      icon: Building2,
      title: 'Future Scope Insights',
      description: 'Explore salary trends, top hiring companies, and industry demand for your career.',
      color: 'from-rose-500 to-pink-600'
    },
    {
      icon: MessageCircle,
      title: 'PlinkX AI Assistant',
      description: '24/7 AI chatbot to answer your career and course-related questions instantly.',
      color: 'from-indigo-500 to-violet-600'
    },
    {
      icon: Briefcase,
      title: 'Job Readiness & Opportunities',
      description: 'Evaluate your job readiness, discover relevant job portals, and get upskilling plans.',
      color: 'from-blue-500 to-cyan-600'
    }
  ];

  const stats = [
    { value: '50+', label: 'Courses Available', icon: BookOpen },
    { value: '10+', label: 'Career Paths', icon: Route },
    { value: '100%', label: 'AI-Powered', icon: Brain },
    { value: '24/7', label: 'AI Support', icon: MessageCircle }
  ];

  const testimonials = [
    { name: 'Priya S.', role: 'Aspiring Data Scientist', quote: 'The roadmap feature helped me plan my entire learning journey!', rating: 5 },
    { name: 'Rahul M.', role: 'Web Developer', quote: 'Finally found courses that actually match my career goals.', rating: 5 },
    { name: 'Ananya K.', role: 'ML Engineer', quote: 'The skill gap analysis showed me exactly what I was missing.', rating: 5 }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-50 to-white dark:from-slate-950 dark:to-background relative">
      <Navbar />

      {/* Hero Section */}
      <section className="relative overflow-hidden pt-24 pb-16 md:pt-32 md:pb-24">
        {/* Background Elements */}
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute top-20 left-10 w-72 h-72 bg-violet-400/20 rounded-full blur-3xl animate-pulse" style={{ animationDuration: '4s' }} />
          <div className="absolute top-40 right-20 w-96 h-96 bg-blue-400/20 rounded-full blur-3xl animate-pulse" style={{ animationDuration: '6s' }} />
          <div className="absolute bottom-20 left-1/3 w-80 h-80 bg-cyan-400/20 rounded-full blur-3xl animate-pulse" style={{ animationDuration: '5s' }} />
        </div>

        <div className="container mx-auto px-4 relative z-10">
          <div className="max-w-5xl mx-auto text-center">
            {/* Badge */}
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-violet-100 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300 text-sm font-medium mb-6 animate-pulse">
              <Sparkles className="h-4 w-4" />
              Developed by Team PlinkX
            </div>

            <h1 className="text-4xl md:text-5xl lg:text-7xl font-bold mb-6 bg-gradient-to-r from-slate-900 via-violet-800 to-blue-900 dark:from-white dark:via-violet-200 dark:to-blue-200 bg-clip-text text-transparent leading-tight">
              Your AI-Powered Academic
              <br />
              <span className="bg-gradient-to-r from-violet-600 to-blue-600 bg-clip-text text-transparent">
                and Career Navigator
              </span>
            </h1>

            <p className="text-lg md:text-xl text-muted-foreground mb-8 max-w-3xl mx-auto leading-relaxed">
              Discover academic content, personalized course recommendations, identify skill gaps, evaluate job readiness, get AI-generated roadmaps,
              and explore future career opportunities — all tailored to your unique goals.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center mb-12">
              <Link to="/signup">
                <Button size="lg" className="w-full sm:w-auto text-lg px-8 py-6 bg-gradient-to-r from-violet-600 to-blue-600 hover:from-violet-700 hover:to-blue-700 shadow-lg shadow-violet-500/25">
                  <Rocket className="mr-2 h-5 w-5" />
                  Start Your Journey
                </Button>
              </Link>
              <a href="#features">
                <Button size="lg" variant="outline" className="w-full sm:w-auto text-lg px-8 py-6 border-2">
                  Explore Features
                  <ChevronRight className="ml-2 h-5 w-5" />
                </Button>
              </a>
            </div>

            {/* Stats Bar */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 max-w-3xl mx-auto">
              {stats.map((stat, index) => (
                <div key={index} className="p-4 rounded-xl bg-white/50 dark:bg-slate-800/50 backdrop-blur-sm border border-slate-200 dark:border-slate-700">
                  <stat.icon className="h-6 w-6 text-violet-600 mx-auto mb-2" />
                  <div className="text-2xl font-bold text-foreground">{stat.value}</div>
                  <div className="text-sm text-muted-foreground">{stat.label}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>


      {/* Features Section */}
      <section id="features" className="py-16 md:py-24 bg-slate-50/50 dark:bg-slate-900/50">
        <div className="container mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Everything You Need to
              <span className="bg-gradient-to-r from-violet-600 to-blue-600 bg-clip-text text-transparent"> Succeed</span>
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto text-lg">
              Our comprehensive platform provides all the tools and insights you need to navigate your career path.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-7xl mx-auto">
            {features.map((feature, index) => (
              <Card key={index} className="group hover:shadow-xl transition-all duration-300 hover:-translate-y-2 border-2 hover:border-violet-200 dark:hover:border-violet-800 overflow-hidden">
                <CardHeader className="pb-4">
                  <div className={`w-14 h-14 rounded-xl bg-gradient-to-br ${feature.color} flex items-center justify-center mb-4 shadow-lg group-hover:scale-110 transition-transform`}>
                    <feature.icon className="h-7 w-7 text-white" />
                  </div>
                  <CardTitle className="text-xl group-hover:text-violet-600 transition-colors">{feature.title}</CardTitle>
                  <CardDescription className="text-base">{feature.description}</CardDescription>
                </CardHeader>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-16 md:py-24">
        <div className="container mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              How It <span className="bg-gradient-to-r from-violet-600 to-blue-600 bg-clip-text text-transparent">Works</span>
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto text-lg">
              Get started in just 3 simple steps
            </p>
          </div>

          <div className="max-w-5xl mx-auto">
            <div className="grid md:grid-cols-3 gap-8">
              {[
                {
                  step: '1',
                  title: 'Create Your Profile',
                  description: 'Tell us about your skills, interests, and dream career. The more details, the better recommendations!',
                  icon: Users,
                  color: 'bg-violet-500'
                },
                {
                  step: '2',
                  title: 'Get AI Recommendations',
                  description: 'Our AI analyzes your profile and matches you with the best courses, identifies skill gaps, and shows future scope.',
                  icon: Zap,
                  color: 'bg-blue-500'
                },
                {
                  step: '3',
                  title: 'Start Learning',
                  description: 'Generate a personalized roadmap, track your progress, and access courses from top platforms worldwide.',
                  icon: GraduationCap,
                  color: 'bg-emerald-500'
                }
              ].map((step, index) => (
                <div key={index} className="relative text-center">
                  {/* Connector Line */}
                  {index < 2 && (
                    <div className="hidden md:block absolute top-12 left-[60%] w-[80%] h-0.5 bg-gradient-to-r from-slate-300 to-transparent dark:from-slate-700" />
                  )}

                  <div className={`w-24 h-24 ${step.color} rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-xl relative`}>
                    <step.icon className="h-12 w-12 text-white" />
                    <div className="absolute -top-2 -right-2 w-8 h-8 rounded-full bg-white dark:bg-slate-800 border-2 border-slate-200 dark:border-slate-700 flex items-center justify-center text-sm font-bold">
                      {step.step}
                    </div>
                  </div>
                  <h3 className="text-xl font-semibold mb-2">{step.title}</h3>
                  <p className="text-muted-foreground">{step.description}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-16 md:py-24 bg-gradient-to-br from-violet-600 to-blue-700 text-white relative overflow-hidden">
        <div className="absolute inset-0 opacity-10">
          <div className="absolute top-10 left-20 w-40 h-40 border border-white rounded-full" />
          <div className="absolute bottom-20 right-40 w-60 h-60 border border-white rounded-full" />
        </div>

        <div className="container mx-auto px-4 relative z-10">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              What Students Say
            </h2>
            <p className="text-white/80 max-w-2xl mx-auto text-lg">
              Join thousands of students who've found their path
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-6 max-w-5xl mx-auto">
            {testimonials.map((testimonial, index) => (
              <div key={index} className="bg-white/10 backdrop-blur-sm rounded-2xl p-6 border border-white/20">
                <div className="flex gap-1 mb-4">
                  {[...Array(testimonial.rating)].map((_, i) => (
                    <Star key={i} className="h-5 w-5 fill-yellow-400 text-yellow-400" />
                  ))}
                </div>
                <p className="text-white/90 mb-4 italic">"{testimonial.quote}"</p>
                <div>
                  <div className="font-semibold">{testimonial.name}</div>
                  <div className="text-white/60 text-sm">{testimonial.role}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 md:py-24">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto text-center">
            <div className="p-8 md:p-12 rounded-3xl bg-gradient-to-br from-slate-900 to-slate-800 text-white relative overflow-hidden">
              <div className="absolute top-0 right-0 w-64 h-64 bg-violet-500/20 rounded-full blur-3xl" />
              <div className="absolute bottom-0 left-0 w-48 h-48 bg-blue-500/20 rounded-full blur-3xl" />

              <div className="relative z-10">
                <Award className="h-16 w-16 text-violet-400 mx-auto mb-6" />
                <h2 className="text-3xl md:text-4xl font-bold mb-4">
                  Ready to Shape Your Future?
                </h2>
                <p className="text-white/80 mb-8 text-lg max-w-2xl mx-auto">
                  Join UniPulse today and get personalized recommendations, AI-powered roadmaps,
                  and expert career insights — all for free!
                </p>
                <Link to="/signup">
                  <Button size="lg" className="text-lg px-8 py-6 bg-gradient-to-r from-violet-500 to-blue-500 hover:from-violet-600 hover:to-blue-600">
                    Get Started for Free
                    <ArrowRight className="ml-2 h-5 w-5" />
                  </Button>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border bg-slate-50 dark:bg-slate-900/50">
        <div className="container mx-auto px-4 py-12">
          <div className="grid md:grid-cols-4 gap-8 mb-8">
            <div className="md:col-span-2">
              <div className="flex items-center gap-2 mb-4">
                <GraduationCap className="h-8 w-8 text-violet-600" />
                <span className="text-xl font-bold">UniPulse</span>
              </div>
              <p className="text-muted-foreground max-w-md">
                Empowering students with a Full AI Academic-to-Employment Intelligence Platform to navigate their career paths with confidence.
              </p>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Features</h4>
              <ul className="space-y-2 text-muted-foreground">
                <li>Course Recommendations</li>
                <li>Skill Gap Analysis</li>
                <li>AI Roadmap</li>
                <li>Future Scope</li>
                <li>Job Readiness</li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Quick Links</h4>
              <ul className="space-y-2 text-muted-foreground">
                <li><Link to="/signup" className="hover:text-violet-600 transition-colors">Get Started</Link></li>
                <li><Link to="/login" className="hover:text-violet-600 transition-colors">Sign In</Link></li>
                <li><a href="#features" className="hover:text-violet-600 transition-colors">Features</a></li>
              </ul>
            </div>
          </div>
          <div className="border-t border-border pt-8 text-center text-muted-foreground">
            <p>© 2026 UniPulse. Built with ❤️ for students worldwide.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
